### ISSUE TITLE
[meta] 将 openEuler RISC-V 项目的日产管理从gitee和微信群转入到gh/issues（9月1日前完成切换）

### ISSUE THREAD

**Issue by lazyparser** [plctlab/openEuler-riscv#1]
如题。

那么，我们开始吧！

**Comment by lazyparser** [comment]
我希望从8月25日开始，不用在微信群里更新进展，而是按照各自认领的任务，更新issues

吴洁可以写一个自动化的脚本抓取所有的issues的最后提交时间，进行排序看看活跃度。

**Comment by xijing21** [comment]
**gitee任务管理向github转移：**
根据当前gitee定位【PLCT外交】、github定位【内部管理】，我根据任务的基本情况作出以下安排：
1. gitee上前期已创建的任务，主要是在华为搭建的obs在线构建环境下去分析解决failed包，这些任务如有问题，需跟华为沟通协调，未完成的任务继续在gitee上跟踪，不转移到当前github下。
2. 前两天安排的本地构建任务，席静在github上补充任务，按照包名创建人物，指派到人

【原则】：所有PLCT任务管理都在github上，只有出现需要跟【外部（华为、其它）】进行沟通反馈，想通过外部力量解决问题的，就在gitee中新建issue。

**微信群管理向github转移：**
所有任务都在github创建和状态更新，问题交流。微信群作为沟通辅助。

**Comment by xijing21** [comment]
- [ ] github补充本地构建任务
- [ ] gitee oerv-work wiki迁移
- [ ] 更新管理要求wiki
