### ISSUE TITLE
请项目组各实习生和员工登记github账号

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#11]
请大家将自己的github 账号在本issue中记录下来

**Comment by xijing21** [comment]
席静
 GitHubID ：xijing21

**Comment by jiewu-plct** [comment]
吴洁
GitHubID: jiewu-plct

**Comment by asdf1113** [comment]
李诗洋
GitHubID : asdf1113

**Comment by mc964203886** [comment]
马驰
GitHubID ：mc964203886

**Comment by xinminst** [comment]
许志凌
GitHubID: xinminst

**Comment by MaximSuen** [comment]
孙浩翔
MaximSuen

**Comment by Wenxiang233** [comment]
邹通成
GitHubID: Wenxiang233

**Comment by liujiawei929** [comment]
刘佳伟
GitHubID:liujiawei929

**Comment by glutinous-rice-wine** [comment]
许嘉玲
GitHubID:glutinous-rice-wine

**Comment by zxs-un** [comment]
孙喆炘
GitHubID: zxs-un

**Comment by YuXiang-ZhuanSun** [comment]
颛孙宇翔
Duplicate of #
GithubID : YuXiang-ZhuanSun

**Comment by lazyparser** [comment]
看起来已经登记到了 members.md

**Comment by yxychristina** [comment]
杨心仪
GitHubID ：yxychristina

**Comment by WenZhixiang** [comment]
温智翔
GitHubID ：WenZhixiang

**Comment by futaaaa** [comment]
付添翼
GitHubID:futaaaa

**Comment by BigBrotherJu** [comment]
金钜涵
GitHubID: BigBrotherJu
