### ISSUE TITLE
RISC-V源码仓包list

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#110]
需要整理的包：https://gitee.com/riscv-spare/projects

当前的包信息：https://gitee.com/xijing666/RISC-V/blob/master/configuration/RISC-V_list.yaml

输出格式要求参考：https://gitee.com/openeuler/community/blob/master/repository/openeuler.yaml

照openeuler.yaml这个格式，里边的把riscv-spare的仓摘出来就行了
name: api-guarder 

description: A tool to generate interface changes 

branches: 

name: master 

type: protected 

type: public

提交要求：
提交到gitee仓库

**Comment by liujiawei929** [comment]
收到，我先试着做一下rv_spare仓库的前10个包。尝试整理然后反馈，其他同学有兴趣可以从前10个之后开始整理。

**Comment by liujiawei929** [comment]
[初步提交PR](https://gitee.com/openeuler/RISC-V/pulls/59)。
等待检查。

**Comment by xijing21** [comment]
转移到gitee管理：https://gitee.com/openeuler/RISC-V/issues/I49D0H?from=project-issue#note_6605354_link

后续状态更新和提交到gitee riscv仓库

**Comment by xijing21** [comment]
提交PR并合并：https://gitee.com/openeuler/RISC-V/pulls/61

关闭issue
