### ISSUE TITLE
[xfce]D1烧录完openEuler image, 启动后设置new password,有些字符的组合无法设置

### ISSUE THREAD

**Issue by jiewu-plct** [plctlab/openEuler-riscv#112]
image: /home/plct/openEuler-D1-xfce-docker.img.bz2

设置密码为1qaz2wsx!@或者qwer1234#$都会提示BAD PASSWORD，这个密码是不是需要满足一定的规则？

![password](https://user-images.githubusercontent.com/89007492/132659954-ad1fe8b4-f30a-45c6-8ce1-dc929aec92b8.jpg)

**Comment by lazyparser** [comment]
有可能。
`1234`
或者
`qwer`
是理所当然的BAD 😄

**Comment by lazyparser** [comment]
我觉得符合逻辑。
