### ISSUE TITLE
获取obs 目前unresolvable 但部分是succeeded的软件包列表

### ISSUE THREAD

**Issue by GeassCore** [plctlab/openEuler-riscv#117]
两个链接:
https://build.openeuler.org/project/monitor/openEuler:Mainline:RISC-V?arch_riscv64=1&defaults=0&repo_standard_riscv64=1&succeeded=1
https://build.openeuler.org/project/monitor/openEuler:Mainline:RISC-V?arch_riscv64=1&defaults=0&repo_standard_riscv64=1&unresolvable=1

举例：
https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/pacemaker 是依赖不满足的
nothing provides libqb-devel >= 0.13.0, nothing provides corosynclib-devel >= 2.0.0
但
https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/libqb 其实是成功的
由于平台目前不能开启自身循环编译，会导致包blocked和多次循环重编译
并且有些底层包，平台编译并不成功，或者无限制编译

**Comment by xijing21** [comment]
补上传下分析结果：
[packagelist_wip-xj.xlsx](https://github.com/plctlab/openEuler-riscv/files/7214237/packagelist_wip-xj.xlsx)

详见[对比结果]标签页
