### ISSUE TITLE
[broken练习] log4j,boost,efl

### ISSUE THREAD

**Issue by yxychristina** [plctlab/openEuler-riscv#119]
我在openEuler：Mainline：RISC-V中找到了构建结果为result的包，选择efl，boost，log4j进行练习，以下说明以log4j为例，另外二者方法类似
1，在包中通过show unmerged找到branch package
2，手动添加repositories，将log4j包branch到自己的project里面
3，下载一个log4j的_service文件修改url为一般默认下的src-openeuler下对应的源；revision用包对应repo的最新版commitID
4，在source files 中add file 
结果是：unresolvable

**Comment by xijing21** [comment]
建议给出截图或者obs该包运行的链接
