### ISSUE TITLE
[meta] 将未被src-openeuler接受的pr提到openeuler-risc-v仓

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#128]
openeuler-risc-v的创建和流程的变更后，需要我们配合将之前的PR进行撤回或者转移。具体如下：
1. 按照谁向src-openeuler提交的PR，谁撤回的原则，自行将各自的pr撤回（已经撤回或者关闭的请忽略）
2. 将自己之前完成的软件包的修改，重新提交PR到openeuler-risc-v
3. 等待openeuler-risc-v 合并后，在obs上更新_service

**Comment by xijing21** [comment]
@liujiawei929  将https://gitee.com/src-openeuler/tss2/pulls/5 PR请求撤回，并将tss2源码的修改重新并入到https://gitee.com/openeuler-risc-v/tss2 中。
修改obs中对应的_service 中的url信息，并提交。

**Comment by xijing21** [comment]
[x265适配riscv64](https://gitee.com/riscv-spare/x265/pulls/1)
[tbb适配riscv64](https://gitee.com/riscv-spare/tbb/pulls/2)
[file适配riscv64升级](https://gitee.com/riscv-spare/file/pulls/1)

@zxs-un 请将这3个包重新提交到openeuler-risc-v中，协助完成仓库迁移。如有遗漏的其它PR，请执行补充并重新提交到openeuler-risc-v中。

**Comment by xijing21** [comment]
李诗洋：

https://gitee.com/openeuler-risc-v/ck/pulls/1

https://gitee.com/src-openeuler/itrustee_sdk/pulls/7   closed 本包架构强相关，不建议在riscv架构下进行编译，将关闭本PR

https://gitee.com/src-openeuler/efibootmgr/pulls/14  open 当前仓库存在保护分支 

https://gitee.com/src-openeuler/edac-utils/pulls/6  open 当前仓库存在保护分支 

https://gitee.com/src-openeuler/qrencode/pulls/3  open 当前仓库存在保护分支

**Comment by xijing21** [comment]
python-jaraco-collections：https://gitee.com/src-openeuler/python-jaraco-collections/pulls/2 
已合并 

python-mistune   obs PR待处理
python-urwid       obs PR待处理


@MaximSuen 下面这两个包只看到了obs的request，没有对应gitee的PR？（我看你spec修改了）

**Comment by xijing21** [comment]
许志凌

gdbus-codegen-glibmm: https://gitee.com/src-openeuler/gdbus-codegen-glibmm/pulls/4  open 当前仓库存在保护分支 

@xinminst 请将gdbus-codegen-glibmm重新提交到openeuler-risc-v中，协助完成仓库迁移。除了下面的配置riscv64的pr待定，如有遗漏的其它PR，请执行补充并重新提交到openeuler-risc-v中。

---

https://gitee.com/src-openeuler/acpid/pulls/15  open 当前仓库存在保护分支 

https://gitee.com/src-openeuler/color-filesystem/pulls/8  open 当前仓库存在保护分支 

https://gitee.com/src-openeuler/docker-anaconda-addon/pulls/3   open 当前仓库存在保护分支 【吕晓倩也做了这个包：目前并入被拒绝：不适合riscv应用场景的包】

https://gitee.com/src-openeuler/dmidecode/pulls/3  open 当前仓库存在保护分支

**Comment by xijing21** [comment]
邹通成：

kmod-kvdo  配置riscv64:https://gitee.com/src-openeuler/kmod-kvdo/pulls/10  open 当前仓库存在保护分支 
libipt   配置riscv64: https://gitee.com/src-openeuler/libipt/pulls/14   open 当前仓库存在保护分支 
openblas  配置riscv64:https://gitee.com/src-openeuler/openblas/pulls/8   open 当前仓库存在保护分支

**Comment by xijing21** [comment]
| 包名                  | PR链接                                                       | PR状态 | 如何处理该包（是否引入riscv构建？）                        | 包简介                                                       |
| --------------------- | ------------------------------------------------------------ | ------ | ---------------------------------------------------------- | ------------------------------------------------------------ |
| itrustee_sdk          | https://gitee.com/src-openeuler/itrustee_sdk/pulls/7         | closed | 本包架构强相关，不建议在riscv架构下进行编译，将关闭本PR    |                                                              |
| efibootmgr            | https://gitee.com/src-openeuler/efibootmgr/pulls/14          | open   |                                                            | efibootmgr是用于管理  UEFI 引导条目的工具。          它不是引导加载程序。它是一种与系统的 EFI 固件交互的工具，它本身充当引导加载程序。使用efibootmgr可以创建、重组和删除引导条目。 |
| edac-utils            | https://gitee.com/src-openeuler/edac-utils/pulls/6           | open   | 本包架构强相关，不建议在riscv架构下进行编译                | EDAC (Error Detection and  Correction) is a set of Linux kernel     modules that handle reporting of hardware-related errors. Currently     these modules mainly handle detection of ECC memory errors for many     x86 and x86-64 chipsets and PCI bus parity errors. |
| acpid                 | https://gitee.com/src-openeuler/acpid/pulls/15               | open   |                                                            | acpid2是一个灵活且可扩展的守护进程，用于传送ACPI  事件。当事件发生时，它执行程序来处理该事件。这些事件由某些操作触发，例如：          按特殊键，包括电源/睡眠/暂停按钮     关闭笔记本盖子     (Un)从笔记本插入交流电源适配器     (Un) 插入电话插孔等。 |
| color-filesystem      | https://gitee.com/src-openeuler/color-filesystem/pulls/8     | open   |                                                            |                                                              |
| docker-anaconda-addon | https://gitee.com/src-openeuler/docker-anaconda-addon/pulls/3 | open   | 暂时不明确是否有riscv使用场景，暂时不考虑加入包到riscv工程 | Anaconda kickstart Docker  插件          这个插件添加了一个名为 com_redhat_docker 的 kickstart 部分，允许     用户在重新启动之前在他们新安装的系统上运行 docker。 |
| dmidecode             | https://gitee.com/src-openeuler/dmidecode/pulls/3            | open   |                                                            | dmidecode是一种工具，用于以人类可读的格式转储计算机的DMI（有人说  SMBIOS）表内容。此表包含系统硬件组件的描述，以及其他有用的信息，例如序列号和BIOS修订版。多亏了这个表，您可以检索这些信息，而不必探查实际的硬件。虽然这在报告速度和安全性方面是一个好点，但这也使得所呈现的信息可能不可靠。 |
| kmod-kvdo             | https://gitee.com/src-openeuler/kmod-kvdo/pulls/10           | open   |                                                            | A pair of kernel modules which  provide pools of deduplicated and/or compressed block storage.          目前其它linux操作系统都只支持x86_64和aarch64           https://centos.pkgs.org/7/centos-x86_64/kmod-kvdo-6.1.3.23-5.el7.x86_64.rpm.html |
| libipt                | [https://gitee.com/src-openeuler/libipt/pulls/14 ](https://gitee.com/src-openeuler/libipt/pulls/14) | open   | intel处理器相关，不需要加入包到riscv工程                   | Intel(R) Processor Trace Decoder  Library     ========================================          The Intel Processor Trace (Intel PT) Decoder Library is Intel's  reference     implementation for decoding Intel PT.   It can be used as a standalone library or     it can be partially or fully integrated into your tool. |
| openblas              | https://gitee.com/src-openeuler/openblas/pulls/8             | open   |                                                            | github.com/xianyi/OpenBLAS          OpenBLAS 是基于 GotoBLAS2 1.13 BSD 版本的优化 BLAS（基本线性代数子程序）库。          RISC-V     C910V：通过 RISC-V 矢量扩展 0.7.1 优化了 3 级 BLAS（真实）和 1,2 级。 |
| lwip                  | [https://gitee.com/src-openeuler/lwip/pulls/3 ](https://gitee.com/src-openeuler/lwip/pulls/3) | open   |                                                            | lwIP（轻量级 IP）是一种广泛使用的开源 TCP/IP  堆栈，专为嵌入式系统设计。LWIP的最初是由发达国家的Adam Dunkels在瑞典计算机科学研究所，现在由开发商的全球网络开发和维护。          lwIP 被许多嵌入式系统制造商使用，包括Intel/Altera、Analog Devices、[1] Xilinx、[2]  TI、STMicro和Freescale。          https://github.com/oaktree11/lwip-riscv-qemu |
| mcelog                | https://gitee.com/src-openeuler/mcelog/pulls/13              | open   | x86，不需要加入包到riscv工程                               | mcelog logs and accounts machine  checks (in particular memory, IO, and CPU hardware errors) on modern x86  Linux systems. |
| microcode_ctl         | [https://gitee.com/src-openeuler/microcode_ctl/pulls/7 ](https://gitee.com/src-openeuler/microcode_ctl/pulls/7) | open   |                                                            | microcode_ctl 实用程序是由 Tigran  Aivazian < tigran@aivazian.fsnet.co.uk >编写的 IA32 微码驱动程序的配套工具。     a)它解码并将新的微码发送到内核驱动程序以上传到英特尔 IA32 处理器。（奔腾 Pro、PII、赛扬、PIII、至强、奔腾 4 等）          b)它通知内核驱动程序释放包含实际应用于给定 CPU 的微码数据副本的缓冲区，每个 CPU 2048 字节的线性阵列，有关块缓冲区布局的信息，请参见  include/asm/processor.h 中的 struct microcode可能持有          微码更新是不稳定的，需要在每次系统启动时上传，即它不会永久刷新您的 CPU，重新启动并恢复到旧微码。 |

**Comment by xijing21** [comment]
@GeassCore 上表中的包，我初步查询了一下，有些包明确可以不加入到riscv工程了。但是还有一些包不是很清楚的，请问你了解么，希望能给出建议：该包是否支持riscv架构，是否需要加入到riscv工程中。

**Comment by MaximSuen** [comment]
> 孙浩翔：
> python-jaraco-collections：https://gitee.com/src-openeuler/python-jaraco-collections/pulls/2
> 已合并
> 
> python-mistune obs PR待处理
> python-urwid obs PR待处理
> https://build.openeuler.org/project/show/home:maxim.suen:branches:openEuler:Mainline:RISC-V

python-urwid 的OBS PR已被张旭舟老师accept了：[链接](https://build.openeuler.org/request/show/333)

**Comment by zxs-un** [comment]
> 
> 
> [x265适配riscv64](https://gitee.com/riscv-spare/x265/pulls/1)
> [tbb适配riscv64](https://gitee.com/riscv-spare/tbb/pulls/2)
> [file适配riscv64升级](https://gitee.com/riscv-spare/file/pulls/1)
> 
> @zxs-un 请将这3个包重新提交到openeuler-risc-v中，协助完成仓库迁移。如有遗漏的其它PR，请执行补充并重新提交到openeuler-risc-v中。

已提交PR
- [x265](https://gitee.com/openeuler-risc-v/x265/pulls/1)
- [tbb](https://gitee.com/openeuler-risc-v/tbb/pulls/1)
- [file](https://gitee.com/openeuler-risc-v/file/pulls/1)

**Comment by xinminst** [comment]
> 许志凌
> 
> gdbus-codegen-glibmm: https://gitee.com/src-openeuler/gdbus-codegen-glibmm/pulls/4 open 当前仓库存在保护分支
> 
> @xinminst 请将gdbus-codegen-glibmm重新提交到openeuler-risc-v中，协助完成仓库迁移。除了配置riscv64的pr待定，如有遗漏的其它PR，请执行补充并重新提交到openeuler-risc-v中。

新PR：[https://gitee.com/openeuler-risc-v/gdbus-codegen-glibmm/pulls/1](https://gitee.com/openeuler-risc-v/gdbus-codegen-glibmm/pulls/1)

**Comment by xijing21** [comment]
good。所有链接提出的包均已提交PR。
