### ISSUE TITLE
[meta] obs构建状态与包依赖关系分析结果

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#137]
使用srcipt/dependent_package下的工具，分析的结果如下：
[obsBuild-20210917-1354.xlsx](https://github.com/plctlab/openEuler-riscv/files/7189142/obsBuild-20210917-1354.xlsx)

能够方便的查看包的构建状态，依赖项的数量，被依赖的情况，初步帮助了解包的重要性。供参考，后续持续更新

**Comment by xijing21** [comment]
上述的数据存在一个问题：
通过getspec.py  执行该文件可获取openEuler-riscv的所有包的spec，获取到的spec存放在specfile.json中specfile.json  存放openEuler-riscv的所有包的spec信息
——————
这个获取的数据是1000个数据项，对包总数4000+对不上，主要原因是gitee网页和接口对可查询的数量做了限制：只能1000个。

后续考虑从本地文件中去查询，完善数据

**Comment by lazyparser** [comment]
可以从 code.tarsier-ci.org 中爬取。

**Comment by xijing21** [comment]
从gitee_ws/RISC-V/configuration/obs_meta/openEuler:Mainline:RISC-V  获取的文件夹数量为4110个。且部分数据依然与obs上构建的包对应不上。
| gitee/RISC-V/configuration/obs_meta/openEuler:Mainline:RISC-V有，obs没有的 | obs有，gitee/RISC-V/configuration/obs_meta/openEuler:Mainline:RISC-V没有的 |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| allpkgs.log                                                  | appstream                                                    |
| guacamole                                                    | atlas                                                        |
| kernel                                                       | js-jquery2                                                   |
| rubygems-ronn                                                | mozjs52                                                      |
|                                                              | ocaml-extlib                                                 |
|                                                              | qtwebkit                                                     |
|                                                              | spice-parent                                                 |
|                                                              |                                                              |




因此，直接从obs的overview中的开发接口中抓取接口url，获取全部的4127个包。其中4115个能够在源码仓中找到对应的源码和spec文件。

还有12个找不到源码，它们是：
Not Found Project: args4j;geronimo-interceptor;jarjar;jatl;java-base64;jsch-agent-proxy;libkate;libofa;liboggz;liboil;mybatis-generator;yyyxxx


对obs上的能够找到spec文件的4115个包进行依赖项分析：

**Comment by xijing21** [comment]
本issue完成，暂时关闭，后续当obs总包变化，obs构建状态变化时，需要执行相应脚本并更新文档。
