### ISSUE TITLE
[构建失败][unresolvable] libdap

### ISSUE THREAD

**Issue by MaximSuen** [plctlab/openEuler-riscv#140]
依赖 `curl = 7.66.0-2.oe1`，目前已在个人账户OBS构建成功（[链接](https://build.openeuler.org/package/show/home:maxim.suen:branches:openEuler:Mainline:RISC-V/curl)），本地osc build复现成功，但是不知道怎么添加到`libdap`构建的过程中去

**Comment by asdf1113** [comment]
obs端验证可参考 https://gitee.com/openeuler/RISC-V/issues/I45FRB?from=project-issue#git-comment-divider
验证成功后告诉 xijing21 将curl加入依赖仓

**Comment by MaximSuen** [comment]
> obs端验证可参考 https://gitee.com/openeuler/RISC-V/issues/I45FRB?from=project-issue#git-comment-divider
> 验证成功后告诉 xijing21 将curl加入依赖仓

OK

**Comment by MaximSuen** [comment]
将`libdap`依赖的`curl = 7.66.0-2.oe1`构建成功后加入了个人branch的依赖库，`libdap`构建成功

**Comment by MaximSuen** [comment]
最新状态：
更改了curl-devel为libcurl-devel，不需再构建低版本curl
