### ISSUE TITLE
[构建失败] fwupd、libsecret

### ISSUE THREAD

**Issue by MaximSuen** [plctlab/openEuler-riscv#144]
等待将`python-3parameterized`、`python3-nose2`、`python-cov-core`添加到依赖库

**Comment by MaximSuen** [comment]
类似问题：[pytest](https://github.com/plctlab/openEuler-riscv/issues/107)

**Comment by lazyparser** [comment]
看起来是一个 easy task？

**Comment by MaximSuen** [comment]
> 看起来是一个 easy task？

跟之前的pytest一样，只是依赖出了问题。但是OBS仓里明明有相应版本的依赖，却还是unresolable的状态

**Comment by GeassCore** [comment]
Mainline:RISC-V的依赖仓是：
openEuler:selfbuild:function/zhangxz_riscv64(没有python-cov-core但是有python-cov-core的编译依赖)
openEuler:selfbuild:function/openEuler_stage1(没有python-cov-core但是有python-cov-core的编译依赖)
openEuler:selfbuild:function/new_pack(在人为添加Mainline:RISC-V成功的包，比如python-cov-core)
目前不能开始自身编译的循环，会大大增加编译时间

**Comment by MaximSuen** [comment]
> Mainline:RISC-V的依赖仓是：
> openEuler:selfbuild:function/zhangxz_riscv64(没有python-cov-core但是有python-cov-core的编译依赖)
> openEuler:selfbuild:function/openEuler_stage1(没有python-cov-core但是有python-cov-core的编译依赖)
> openEuler:selfbuild:function/new_pack(在人为添加Mainline:RISC-V成功的包，比如python-cov-core)
> 目前不能开始自身编译的循环，会大大增加编译时间

原来是这样！感谢王老师答疑解惑~
