### ISSUE TITLE
[周期任务] 20210909-20210923 外部可见交付物汇总表

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#149]
请各位项目组成员于9.24之前提交2021.9.9--2021.9.22时间周期内的外部可见交付。

将可见交付直接更新到文档：https://github.com/plctlab/openEuler-riscv/blob/main/weeklyreports/membersAchi9.23.md 中，并提交PR

要求：
请大家参考如下信息要素提交可见交付成果：**（没有的可不列出）**

构建包任务类：

- XXXX包：
  - issue：
  - obs：
  - PR：
  - 文档：

其它任务：

- issue标题：
  - issue链接：
  - PR：
  - 文档：

笔记类（这里特指自己学习、工作中总结的文档，不是以issue方式指定的任务）：

- 文档标题、链接

问题类（工作中发现和遇到的问题，必须以公开的方式可见才行，非可见不算可见交付）

- issue标题和链接

**说明：以后每次双周会的前一天，每个月的月末，都要求定期提交自己的可见交付物，方便同步项目进展。**

**Comment by xijing21** [comment]
@mc964203886 @liujiawei929 @zxs-un @asdf1113 @MaximSuen @xinminst @Wenxiang233 @glutinous-rice-wine @YuXiang-ZhuanSun @ShiHaoGao @YuanZheng612 @LiuYang328 @WenZhixiang @yxychristina 

以上都有

**Comment by MaximSuen** [comment]
**构建包任务类：**

- [OBS中valgrind相关依赖的处理](https://github.com/plctlab/openEuler-riscv/issues/129)

- jq：
  - issue：[链接](https://github.com/plctlab/openEuler-riscv/issues/136)
  - obs：[链接](https://build.openeuler.org/package/show/home:maxim.suen:branches:openEuler:Mainline:RISC-V/jq)
  - PR：[链接](https://gitee.com/openeuler-risc-v/jq/pulls/2)
- libdap:
  - issue：[链接](https://github.com/plctlab/openEuler-riscv/issues/140)
  - obs：[链接](https://build.openeuler.org/package/show/home:maxim.suen:branches:openEuler:Mainline:RISC-V/libdap)
  - PR（待合并）：[链接](https://gitee.com/openeuler-risc-v/libdap/pulls/1)

- fwupd、libsecret:
  - issue:[链接](https://github.com/plctlab/openEuler-riscv/issues/144)
- pytest:
  - issue:[链接](https://github.com/plctlab/openEuler-riscv/issues/107)

**笔记类**

- [smp32版镜像的使用](https://gitee.com/maximsuen/plct-internship-notes/blob/master/7.SMP32%E7%89%88OE%E5%92%8C%E7%9B%B8%E5%BA%94QEMU%E7%9A%84%E4%BD%BF%E7%94%A8.md)

**Comment by LiuYang328** [comment]
在自己的主机上成功搭建好了所有环境，能够通过ssh连接服务器进行工作

选择了2个相对简单的包进行构建学习，目前还在学习中....
[gnu-ef](https://github.com/plctlab/openEuler-riscv/issues/152)
[ant](https://github.com/plctlab/openEuler-riscv/issues/153)

**Comment by mc964203886** [comment]
文档与指导：https://github.com/plctlab/openEuler-riscv/issues/83

**Comment by WenZhixiang** [comment]
1.  [[excluded练习]edac-utils ](https://github.com/plctlab/openEuler-riscv/issues/122)
2.  [[broken练习]efl ](https://github.com/plctlab/openEuler-riscv/issues/120l)
3.  学习了Linux操作系统的常用命令：
https://blog.csdn.net/qq_23329167/article/details/83856430/
4.  在b站上学习了《openEuler构建之OBS使用指导》
5.  在CSDN等论坛学习并整理一些相关名词的解释及用法
6. [学习笔记](https://gitee.com/wen-zhixiang/study-notes/blob/master/0909-0923%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0.md)

**Comment by WenZhixiang** [comment]
1.  [[excluded练习]edac-utils ](https://github.com/plctlab/openEuler-riscv/issues/122)
2.  [[broken练习]efl ](https://github.com/plctlab/openEuler-riscv/issues/120l)
3.  学习了Linux操作系统的常用命令：
https://blog.csdn.net/qq_23329167/article/details/83856430/
4.  在b站上学习了《openEuler构建之OBS使用指导》
5.  在CSDN等论坛学习并整理一些相关名词的解释及用法
6. [学习笔记](https://gitee.com/wen-zhixiang/study-notes/blob/master/0909-0923%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0.md)
7. 选择了[memleax](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/memleax)

**Comment by WenZhixiang** [comment]
1.  [[excluded练习]edac-utils ](https://github.com/plctlab/openEuler-riscv/issues/122)
2.  [[broken练习]efl ](https://github.com/plctlab/openEuler-riscv/issues/120l)
3.  学习了Linux操作系统的常用命令：
https://blog.csdn.net/qq_23329167/article/details/83856430/
4.  在b站上学习了《openEuler构建之OBS使用指导》
5.  在CSDN等论坛学习并整理一些相关名词的解释及用法
6. [学习笔记](https://gitee.com/wen-zhixiang/study-notes/blob/master/0909-0923%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0.md)
7. 选择了[memleax](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/memleax)进行构建学习

**Comment by YuanZheng612** [comment]
构建包任务类
gunlib包：
[issue：](https://github.com/plctlab/openEuler-riscv/issues/155)
[obs：](https://build.openeuler.org/package/show/home:YuanZheng:branches:openEuler:Mainline:RISC-V/gnulib)

笔记类：
[spec文件学习.docx](https://github.com/plctlab/openEuler-riscv/files/7217241/spec.docx)

正在学着看懂构建log，并且studing连接老师提供的服务器进行构建

**Comment by YuanZheng612** [comment]
构建包任务类
gunlib包：
[issue：](https://github.com/plctlab/openEuler-riscv/issues/155)
[obs：](https://build.openeuler.org/package/show/home:YuanZheng:branches:openEuler:Mainline:RISC-V/gnulib)

笔记类：
[spec文件学习.docx](https://github.com/plctlab/openEuler-riscv/files/7217241/spec.docx)

学习了rpm相关命令和功能，正在学着看懂构建log，并且studing连接老师提供的服务器进行构建

**Comment by Wenxiang233** [comment]
### 构建包任务类
#### ldns
- obs构建：[link](https://build.openeuler.org/package/show/home:ChengZou:branches:openEuler:Mainline:RISC-V/ldns)
- issue: [link](https://github.com/plctlab/openEuler-riscv/issues/141)

#### iavf
- obs构建：[link](https://build.openeuler.org/package/show/home:ChengZou:branches:openEuler:Mainline:RISC-V/iavf)

#### i40e
- obs构建: [link](https://build.openeuler.org/package/show/home:ChengZou:branches:openEuler:Mainline:RISC-V/i40e)

**Comment by liujiawei929** [comment]
**包构建任务**
[mozjs52 的状态](https://github.com/plctlab/openEuler-riscv/issues/118)
**学习记录**
[如何给一个包打补丁-mozjs52](https://gitee.com/jiawei__liu/open-euler_riscv64/blob/master/doc/%E4%BF%AE52%E5%8C%85%E7%9A%84%E6%B5%81%E7%A8%8B%E8%AE%B0%E5%BD%95.md)
[在openEuler项目中学到的一些linux操作](https://gitee.com/jiawei__liu/open-euler_riscv64/blob/master/doc/%E5%9C%A8openEuler%E9%A1%B9%E7%9B%AE%E4%B8%AD%E5%AD%A6%E5%88%B0%E7%9A%84%E4%B8%80%E4%BA%9Blinux%E6%93%8D%E4%BD%9C.md)
[记录我关于oe项目的一些疑惑](https://gitee.com/jiawei__liu/open-euler_riscv64/blob/master/doc/openEuler%E9%A1%B9%E7%9B%AE%E7%9B%B8%E5%85%B3%E7%9A%84%E4%B8%80%E4%BA%9B%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5%E7%9A%84%E9%97%AE%E7%AD%94%E8%AE%B0%E5%BD%95.md)

**Comment by zxs-un** [comment]
- [BaseOS_Base20: 19/20](https://build.openeuler.org/project/show/home:yx971:RISC-V:BaseOS:Base20)
- [stage 复现Base OS](https://build.openeuler.org/project/show/home:zxs-un:openEuler:riscv64:BaseOS:stage1)
- [ssh 配置](https://gitee.com/zxs-un/openEuler-port2riscv64/blob/master/doc/ssh-agent-config.md)

**Comment by xinminst** [comment]
http-parser包：
[issue](https://github.com/plctlab/openEuler-riscv/issues/131)
[obs](https://build.openeuler.org/package/show/home:xinminst:branches:openEuler:Mainline:RISC-V/http-parser)
[PR](https://gitee.com/openeuler-risc-v/http-parser/pulls/1)
isomd5sum包：
[issue ](https://github.com/plctlab/openEuler-riscv/issues/132)
[obs](https://build.openeuler.org/package/show/home:xinminst:branches:openEuler:Mainline:RISC-V/isomd5sum)
[PR](https://gitee.com/openeuler-risc-v/isomd5sum/pulls/1)
pixman包：
[issue](https://github.com/plctlab/openEuler-riscv/issues/139)
[obs](https://build.openeuler.org/package/show/home:xinminst:branches:openEuler:Mainline:RISC-V/pixman)
[PR](https://gitee.com/openeuler-risc-v/pixman/pulls/1)

**Comment by ShiHaoGao** [comment]
构建包任务类
gettext
[issue](https://github.com/plctlab/openEuler-riscv/issues/157)
[obs](https://build.openeuler.org/package/show/home:gsh:branches:openEuler:Mainline:RISC-V/gettext)

gspell
[issue](https://github.com/plctlab/openEuler-riscv/issues/156)
[obs](https://build.openeuler.org/package/show/home:gsh:branches:openEuler:Mainline:RISC-V/gspell)

正在学习如何在服务器上使用osc build 和 解决failed的包。

**Comment by glutinous-rice-wine** [comment]
构建包任务：

- sscg【failed包】
    [*issue：sscg](https://github.com/plctlab/openEuler-riscv/issues/147)
    [*obs：sscg](https://build.openeuler.org/package/show/home:nuomi:branches:openEuler:Mainline:RISC-V/sscg)

- apr-util【failed包】
    [*issue](https://github.com/plctlab/openEuler-riscv/issues/159)

笔记类：

- [spec学习](https://gitee.com/sticky-rice-wine/note/blob/master/spec%E8%87%AA%E5%AD%A6.pdf)

**Comment by yxychristina** [comment]
1.我成功连接了ssh服务器，并且装上了openEuler和qemu
2.完成excluded包acpid与bpftrace的成功构建：
[excluded包构建](https://github.com/plctlab/openEuler-riscv/issues/121)
3.完成broken包log4j，boost,efl的构建：
[broken包构建](https://github.com/plctlab/openEuler-riscv/issues/119)
4.[完成Linux操作系统的常用命令的学习]：(https://blog.csdn.net/qq_23329167/article/details/83856430/)和(https://www.bilibili.com/video/BV1H7411K7pZ)
5.完成《openEuler构建之OBS使用指导》的学习
6.[学习笔记](https://gitee.com/yxycrhistina/study-notes/blob/master/README.md)

**Comment by xijing21** [comment]
李诗洋按照要求在文档中编写并提交了。 goooood

**Comment by xijing21** [comment]
12位实习生已经提交， @YuXiang-ZhuanSun 请及时提交

**Comment by YuXiang-ZhuanSun** [comment]
1.自行购买了云服务器，并建立了ssh连接，尝试安装openeuler失败
[2.学习了Linux相关知识，](https://github.com/YuXiang-ZhuanSun/Blog)
3.完成《openEuler构建之OBS使用指导》的学习

**Comment by xijing21** [comment]
汇总到https://github.com/plctlab/openEuler-riscv/blob/main/weeklyreports/membersAchi9.23.md 文档中

所有人都提交，关闭issue
