### ISSUE TITLE
openEuler-D1-wifi-hdmi-docker-20210826.img对chrony的适配问题

### ISSUE THREAD

**Issue by jiangxiaobin96** [plctlab/openEuler-riscv#199]
## openEuler-riscv上部署k8s集群。
- 遇到问题
在部署完etcd后，etcd可以正常运行，但显示grpc无法正常连接
```
rejected connection from "192.168.7.175:56406" (error "tls: failed to verify client certificate: x509: certificate has expired or is not yet valid: current time 2019-09-03T17:28:31+08:00 is before 2021-11-20T05:48:00Z", ServerName "")
```
- 问题定位
因为错误中涉及到了证书的时间问题，所以定位报错到系统时钟同步上。目前在openEuler-riscv上的系统时间为`timedatectl status`
```
[root@k8s-01 chrony-3.2]# timedatectl status
               Local time: Sun 2021-11-21 07:28:04 UTC
           Universal time: Sun 2021-11-21 07:28:04 UTC
                 RTC time: Sun 2021-11-21 07:28:05
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: inactive
          RTC in local TZ: no
```
为了做对比实验，以同样的配置方法在Ubuntu上etcd能够正常运行，其系统时间为
```
root@ubuntu:/# timedatectl status
               Local time: Sun 2021-11-21 07:29:17 UTC
           Universal time: Sun 2021-11-21 07:29:17 UTC
                 RTC time: n/a
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
- 目前尝试过的方法
1. 编译安装了chrony并使其运行起来
2. ntpdate cn.pool.ntp.org
3. hwclock -w # 使硬件时间RTC与系统时间保持一致

**Comment by GeassCore** [comment]
普通环境下:
yum 安装chrony和ntpdate后

```
systemctl enable chronyd.service
systemctl restart chronyd.service
systemctl status chronyd.service(启动失败由于ntp未设置)

ntpdate -u cn.pool.ntp.org
systemctl restart chronyd.service(启动成功)
hwclock -w
```
![image](https://user-images.githubusercontent.com/18118034/142754705-dfd3b075-58d6-40f4-8765-9afdf624b84b.png)

Time zone 存在差异，虽然list-timezones中没有
使用 timedatectl set-timezone "Etc/UTC" 设置?
![image](https://user-images.githubusercontent.com/18118034/142754857-1141edc9-77a4-4392-90ae-21cc3aa14b69.png)

etcd如何部署？目前我使用的软件源中etcd未成功编译

**Comment by jiangxiaobin96** [comment]
etcd的riscv目前还需要通过编译源码获得。
在openEuler-riscv的软件源中我没有匹配到chrony，所以我是通过编译源码的方式安装的。
这里`hwclock -w`的作用是将RTC时间同步到与系统时间相同吗？为什么总是会相差几秒，这个是正常现象吗？

**Comment by GeassCore** [comment]
chrony 可以在这个 http://119.3.219.20:82/openEuler:/Mainline:/RISC-V/standard_riscv64/
软件源获取，可以把这个地址添加到yum的repo中，然后yum clean all && yum makecache 后安装
hwclock -w 是写入RTC吧，本身应该是使用qemu virt中 goldfish_rtc模拟，读取其实是软件模拟过程，可能中间存在时间差异，我觉得可以暂时不管

**Comment by jiangxiaobin96** [comment]
安装时有遇到这样的报错嘛
```
[root@k8s-01 yum.repos.d]# yum install chrony
Last metadata expiration check: 0:02:18 ago on Mon Nov 22 08:10:47 2021.
Error:
 Problem: package chrony-3.5-3.oe1.riscv64 requires timedatex, but none of the providers can be installed
  - package timedatex-0.6-2.oe1.riscv64 requires polkit, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides libmozjs-78.so.0()(64bit) needed by polkit-0.118-2.riscv64
  - nothing provides libmozjs-78.so.0(mozjs_78)(64bit) needed by polkit-0.118-2.riscv64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by jiangxiaobin96** [comment]
openEuler-D1-wifi-hdmi-docker-20210826.img镜像在添加http://119.3.219.20:82/openEuler:/Mainline:/RISC-V/standard_riscv64/ 镜像源后，安装过程出现以下依赖报错。
![7f2f5f7ddd00198ccd4e9947d8522fd](https://user-images.githubusercontent.com/26225317/143350372-0d57899c-a4b0-466c-ae2c-facf6c37c387.png)
![dc5baef10416eb5575efd5ef7906a40](https://user-images.githubusercontent.com/26225317/143350476-fa51f04d-7721-4cb8-a83e-b7c7484621cd.png)

**Comment by lazyparser** [comment]
Hi @jiangxiaobin96 搞定啦？

**Comment by jiangxiaobin96** [comment]
时间搞定了，但是etcd还在测试
