### ISSUE TITLE
请教如何为oe源码包生成patch？

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#206]
请教个如何打patch的问题：
我这边用git format-patch生成了patch文件，但是对于整个操作还是很多疑惑的地方，具体体现在源码是压缩形式tar.bz2存在，我是这样操作的：
1. git clone gitee源码（源码是tar.bz2）
2. 解压源码
3. 修改要修改的源码文件，git commit 、git format-patch
> 这样操作后，就有个问题，patch文件中的文件路径会包含解压源码包信息和路径
4. 删除解压的源码文件
5. 修改spec，将spec、patch提交到gitee上
> 生成的patch文件内容：https://gitee.com/xijing666/pmix/blob/master/Extended-timeout.patch
6. obs修改_service ,构建——》结果失败
> 构建日志：https://build.openeuler.org/package/live_build_log/home:xijing:branches:openEuler:Mainline:RISC-V/pmix/standard_riscv64/riscv64

总感觉这样操作不太对，请问一般大家都怎么操作的呢？如何处理源码是压缩包的情况？

**Comment by xijing21** [comment]
生成的patch文件内容：
https://gitee.com/xijing666/pmix/blob/master/Extended-timeout.patch

**Comment by xijing21** [comment]
一个简单做法就是

解压缩
进入
git init && git add --all && git commit  'init'
修改
git diff > ../patch-file-name
cd ..
删除掉解压缩的目录

---
按照上述方法，已经成功解决问题

**Comment by lazyparser** [comment]
@席静 顺带我注意到 spec 里面可以指定 patch -p1 还是 -p2 ，那样的话
https://github.com/plctlab/openEuler-riscv/issues/206
其实就可以更加简单的改一下，加一行，类似于
https://gitee.com/openeuler-risc-v/kexec-tools/blob/master/kexec-tools.spec#L133

可以试试看能否work？
