### ISSUE TITLE
openEuler-riscv上flannel软件包的适配问题

### ISSUE THREAD

**Issue by jiangxiaobin96** [plctlab/openEuler-riscv#208]
在GitHub上还没有flannel的移植，但是我找到了一个opensuse的flannel的rpm包[flannel-0.14.0-1.1.riscv64.rpm](https://mirrorcache.opensuse.org/ports/riscv/tumbleweed/repo/oss/riscv64/flannel-0.14.0-1.1.riscv64.rpm.mirrorlist)
我在D1-openEuler上尝试了 `rpm -ihv` , 提示有部分包缺失：
```
warning: flannel-0.14.0-1.1.riscv64.rpm: Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
error: Failed dependencies:
        iproute2 is needed by flannel-0.14.0-1.1.riscv64
        net-tools-deprecated is needed by flannel-0.14.0-1.1.riscv64
```
之后我从GitHub上下载克隆了iproute2的源码进行编译：`https://github.com/shemminger/iproute2` 编译安装完成后，依旧显示缺失iproute2。并且第二个包是net-tools过时版，这个我也不能理解。

**Comment by GeassCore** [comment]
> 依旧显示缺失iproute2 

编译包依赖缺失并不会消失，如果系统有库和工具，可以强制安装
> net-tools过时版

需要什么版本？ 2.10 ？ 可以先自编译安装？  flannel目前还没有

**Comment by jiangxiaobin96** [comment]
1. 忽略依赖强制安装，安装后无法正常使用，flanneld --version报错
2. net-tools它也没说需要什么版本，而且我的d1上已经装好了net-tools了，它依旧报net-tools-deprecated缺失

**Comment by jiangxiaobin96** [comment]
编译源码时报错
![image](https://user-images.githubusercontent.com/26225317/143820553-469e4793-d065-4ba0-b301-eb74be99090d.png)

**Comment by jiangxiaobin96** [comment]
d1-openEuler-riscv上还编译不出来，我在debian-riscv上编译成功了，可以编译出flanneld二进制文件
