### ISSUE TITLE
验证在 D1 上跑 openEuler，启动 docker，容器里跑 debian 和 ubuntu

### ISSUE THREAD

**Issue by lazyparser** [plctlab/openEuler-riscv#25]
做一个方案出来。我要在 RISC-V Lab 中使用。

**Comment by lazyparser** [comment]
看起来依赖于 #26 Go 语言还没有。

**Comment by mollybuild** [comment]
执行`journalctl -u containerd.service -f`，看到上面的issue跟CNI有关：
![1630296023(1)](https://user-images.githubusercontent.com/26591790/131283574-4e857c14-05e5-4793-b73a-05de74ace580.png)

**Comment by mollybuild** [comment]
按照https://github.com/containernetworking/cni/ 安装了cni的官方plugins，启动containerd，报错如下：
![fcdeb966a995b019d13b791fb48461c](https://user-images.githubusercontent.com/26591790/131309623-3c98e1d1-30a3-436f-981a-b5751ed1afa3.jpg)

**Comment by mollybuild** [comment]
containerd后台启动，再启动dockerd试试：

![1630312016(1)](https://user-images.githubusercontent.com/26591790/131309914-6364d583-86ea-4523-a1f6-b916c3830382.png)

**Comment by mollybuild** [comment]
上面的错误提示缺少Iptables，安装Iptables:
```shell
yum install -y iptables-services
```
然后再后台启动dockerd：
```
# dockerd >dockerd.log 2>&1 &
```

执行`docker version`:
![1630313752(1)](https://user-images.githubusercontent.com/26591790/131313918-42195024-a291-4150-9ed8-ed862d78a35c.png)


执行`docker run --rm hello-world`
![1630313712(1)](https://user-images.githubusercontent.com/26591790/131313812-8cbd7d2f-bbad-4a4b-af5e-5e7181993666.png)

**Comment by mollybuild** [comment]
拉取Debian内核并且启动docker：
![1630314988(1)](https://user-images.githubusercontent.com/26591790/131316658-dece0880-2822-45ab-b59f-f37d366b08c8.png)

**Comment by lazyparser** [comment]
OK 搞定啦？

**Comment by mollybuild** [comment]
![1630374700(1)](https://user-images.githubusercontent.com/26591790/131428725-586e9ffa-e378-41b3-8a64-93b2117fe949.png)

目前是报找不到libseccomp.so.o，但是我明明有这个库，在/usr/local/lib中，比较困惑：
![1630374807(1)](https://user-images.githubusercontent.com/26591790/131428851-479c8006-6da4-4c86-a523-30409f2b7f19.png)

尝试把/usr/local/lib加到LD_LIBRARY_PATH里面，也没有用。

**Comment by mollybuild** [comment]
前面还包过缺一个yajl相关的库，`yum install yajl-devel` 就可以了

**Comment by lazyparser** [comment]
which runc
ldd `which runc` 
ldd `which runc` |grep libsec

看起来 docker 抱怨的是 runc 错误。是 runc 想找 libseccomp 没找到。那么用 ldd 可以查看 runc 【从那些路径加载什么so】

有可能下载的包，构建的时候默认 libseccmp 的路径不同。

解决方法：

1. 使用 LD_LIBRARY_PATH 或类似的环境变量劫持下，
2. 创建个对应的子目录符号连接，fake下

**Comment by mollybuild** [comment]
![1630375499(1)](https://user-images.githubusercontent.com/26591790/131429855-9a92bc92-80e7-49a9-85d5-70f683f197f3.png)

**Comment by mollybuild** [comment]
没错啊，runc的加载路径就是/usr/local/lib，这个路径是对的啊，困惑

**Comment by lazyparser** [comment]
> 没错啊，runc的加载路径就是/usr/local/lib，这个路径是对的啊，困惑

嗯，奇怪了。重启下试试😄

**Comment by mollybuild** [comment]
dockerd 执行的时候有报错：
![1630379826(1)](https://user-images.githubusercontent.com/26591790/131436087-80ae10b8-56b6-4694-942f-ae708dc6e9c4.png)

**Comment by mollybuild** [comment]
![1630392468(1)](https://user-images.githubusercontent.com/26591790/131455532-0695f1b1-3a1d-48dd-876c-9abafb9a52e5.png)

Done. 上面的问题就是把后台的containerd和dockerd关闭了，重新启动就好了。
看到后台的containerd和dockerd：
```shell
# ps axf | grep containerd
# ps axf | grep dockerd
```

然后用`kill -9`全都关闭，在重启服务：
```shell
# containerd >containerd.log 2>&1 &
# systemctl start docker
```

**Comment by mollybuild** [comment]
D1重启，ps查看就已经有containerd和dockerd进程了。而且在这个时候执行docker run会报错，截图分别如下：
![1630401559(1)](https://user-images.githubusercontent.com/26591790/131477024-433683cf-b312-4d5c-8404-d56f84a022ac.png)

![1630401657(1)](https://user-images.githubusercontent.com/26591790/131477281-35305cd8-125a-423e-804d-71a9c5fbccc4.png)

**Comment by mollybuild** [comment]
又试了一遍，把后台的containerd/dockerd都kill之后，手动开启containerd和docker，docker就可以成功运行了。
![1630401918(1)](https://user-images.githubusercontent.com/26591790/131478025-beebb1ad-184c-4f48-ba51-c901940a823c.png)

**Comment by mollybuild** [comment]
基本上解决了
