### ISSUE TITLE
请大家为自己的github修改name

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#31]
目前，大家的githubID有点难辨认，请大家为自己的github配置下name。
要求name为拼音：如  xijing  

具体操作：
1. 点击右上角头像图标，进入个人页
2. 点击Edit profile，修改name 并保存。
3. 最后检查达到如下效果：
![1630029131(1)](https://user-images.githubusercontent.com/84754181/131058961-2881fd03-a4fa-46b3-b24f-f8fd7e15f39b.png)

**Comment by lazyparser** [comment]
Done？
