### ISSUE TITLE
obs-worker 机器的软件安装汇总贴

### ISSUE THREAD

**Issue by lazyparser** [plctlab/openEuler-riscv#35]
各位使用 tarsier-worker 的实习生和社区开发者：

已经开通了账号，可以登录访问，登录时请注意没有sudo权限，如果有需要安装软件，可以在本issue评论。

```
apt install emacs
```

直接贴这样的命令即可。

**Comment by zxs-un** [comment]
sudo apt install pkg-config mingw-w64

**Comment by lazyparser** [comment]
> sudo apt install pkg-config mingw-w64

安装好了。

**Comment by zxs-un** [comment]
sudo apt install autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev \
                 gawk build-essential bison flex texinfo gperf libtool patchutils bc \
                 zlib1g-dev libexpat-dev git \
                 libglib2.0-dev libfdt-dev libpixman-1-dev \
                 libncurses5-dev libncursesw5-dev

**Comment by lazyparser** [comment]
> sudo apt install autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev git libglib2.0-dev libfdt-dev libpixman-1-dev libncurses5-dev libncursesw5-dev

安装好了

**Comment by lazyparser** [comment]
`apt install obs-build`
