### ISSUE TITLE
[baseos] 包依赖关系分析

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#39]
本issue为 #38 的关联子任务

包和包是存在依赖关系的，目前为了给openEuler riscv  OS梳理一个最小集合的底层依赖包，我们需要分析下包的依赖关系并输出。

分析对象：https://build.openeuler.org/project/show/openEuler:Mainline:RISC-V 中的4128个包
分析目的：梳理这4128个包之前的依赖关系，最终能够得到哪些包是底层包（被上层包所依赖的包）
具体要求：
1. 从4128个包的spec文件中，分析每个包的 BuildRequires（ Requires ？）罗列的包。最终将4128个包的依赖关系通过某种可视化表现形式展示出来，比如：
![image](https://user-images.githubusercontent.com/84754181/131123350-4e99fcf7-14d2-435f-a340-33813e6e2031.png)

可视化表现形式根据难度与 @zxs-un @GeassCore 协商。不要求一定按照上图来。

2. 在spec中，有些依赖关系写的是库，而非包含该库的包名。在oE obs系统中，是通过pkgconf包这个工具去查询的，针对这种情形，我们也需要根据库，找到包，然后在依赖关系中显示包名（而非库）。

以上要求和具体如何实现，可以与 @GeassCore @zxs-un 咨询商议

**Comment by jiewu-plct** [comment]
初版的自动化脚本已上传至https://github.com/plctlab/openEuler-riscv/tree/main/scripts/dependent_package，脚本的使用说明可以参看文件夹中的README.md

**Comment by zxs-un** [comment]
整理Linux发行版基础包列表，第一批75个，Base20与Base50 

https://gitee.com/zxs-un/openEuler-port2riscv64/blob/master/doc/build-obs-baseos-repo.md
