### ISSUE TITLE
写一个脚本，每天早上9点运行一次，抓取所有 PLCT Lab 同学提交给 oE 项目的 MR 的状态，自动生成一个报表（列表）

### ISSUE THREAD

**Issue by lazyparser** [plctlab/openEuler-riscv#40]
背景是这样子的：我们有十几个同学同时在解决 openEuler 4000+个包的构建错误问题。已经提交了几十个MR。但是MR都是需要好几天甚至好几周才会得到review和merge。

负责每天跟进各个MR的人是 @xijing21 ，但是很显然这项工作应该用脚本自动生成，人类去做非常花费时间且枯燥。你看，每日MR报告其实就执行了2天，第三天就没有人提了。

我需要的流程是这样子的：

第一步，实习同学提交了一个MR之后，将这个MR的链接某种形式发给 @xijing21 或者 @jiewu-plct 

第二步， @xijing21 或者 @jiewu-plct 把这个URL添加到脚本的配置文件（一个txt文件，里面一行一个URL）。假设就叫 watchlist.txt 好了。

第三步，设定一个 cron 任务每天9点之前跑一下脚本。这个脚本挨个的去查询下MR的状态，包含【1】open/merge/reviewed/rejected 等；【2】 last comment by humans；【3】过去24小时coments数量。输出一个txt或者CSV文件就行。

第四步，是 bonus 了：能够通过 slack 机器人来触发脚本的执行，并且能够在 slack 里面显示出来。【这是另一个技能树了】

**Comment by jiewu-plct** [comment]
脚本已完成，放在https://github.com/plctlab/openEuler-riscv/tree/main/scripts/Gitee_PRInfo

**Comment by xijing21** [comment]
工具在使用后，发现url：如 https://gitee.com/api/v5/repos/openeuler/RISC-V/pulls/65  返回的是json，不方便查看者阅读，对比界面操作点击后的url（https://gitee.com/openeuler/RISC-V/pulls/65  ）

openeuler-risc-v/存在同样的问题：
https://gitee.com/api/v5/repos/openeuler-risc-v/ck/pulls/1  ——》https://gitee.com/openeuler-risc-v/ck/pulls/1 

因此：只需要在写入文档时，将url进行如下替换：
gitee.com/api/v5/repos/————》gitee.com/

**Comment by jiewu-plct** [comment]
自动化脚本已经修改和更新
