### ISSUE TITLE
[构建失败]【已解决】python-jaraco-collections

### ISSUE THREAD

**Issue by MaximSuen** [plctlab/openEuler-riscv#48]
**Gitee PR：**[链接](https://gitee.com/src-openeuler/python-jaraco-collections/pulls/2)
**解决过程：**
    在spec文件%file字段中添加以下内容，解决python37环境下构建失败问题
```
%exclude %{python3_sitelib}/jaraco/__pycache__/collections.cpython-37.*
```

**Comment by lazyparser** [comment]
good job.

已经解决的 issues 可以记录之后关闭。
