### ISSUE TITLE
[broken练习]efl

### ISSUE THREAD

**Issue by LiuYang328** [plctlab/openEuler-riscv#57]
1. 在openEuler:Mainline:RISC-V 中找到 build result 为 broken 的包， 我选择的是 efl
2. 将efl包 branch 到自己的project 中（我需要手动添加repositories）
3. 下载_service文件，然后根据gitee上的revisoin 和 https，修改service中的revision和url
4. 将修改好的文件add file 到自己的efl包下，然后就出结果了

构建结果：unresolvable: 1

**Comment by xijing21** [comment]
ok，流程正确！

将efl包 branch 到自己的project 中（我需要手动添加repositories）——》这个如果包是通过在openEuler:Mainline:RISC-V branch过来的，依赖关系本身就具备吧？——》不过没关系，能够手动添加依赖仓并执行构建，good

**Comment by xijing21** [comment]
任务完成，可关闭issue
