### ISSUE TITLE
[excluded练习]bpftrace

### ISSUE THREAD

**Issue by LiuYang328** [plctlab/openEuler-riscv#58]
1. 在openEuler:Mainline:RISC-V 中找到 build result 为 excluded 的包， 我选择的是 bpftrace
2. 将bpftrace包 branch 到自己的project 中（我需要手动添加repositories）
3. 在gitee上将bpftrace包fork到自己的仓库，修改spec文件，ExclusiveArch 没有riscv64的，在该字段后面添加riscv64
4. 然后更改_service文件，将url和revision都更新为自己的最新版本，之后就可以看到构建结果

构建结果：unresolvable

**Comment by xijing21** [comment]
下次可以附图，还有unresolvable  状态会有提示信息，缺少什么依赖等。——》更进一步去了解状态和分析问题。

完成任务，关闭issue
