### ISSUE TITLE
[broken练习] log4j

### ISSUE THREAD

**Issue by YuanZheng612** [plctlab/openEuler-riscv#59]
第一步：在openEuler:Mainline:RISC-V中找到build result 为 broken 的包，我选择的是log4j这个包，然后branch到自己的库。
第二部：在gittee中搜索src-openEuler库并在其中找到log4j包，然后fork到自己库。
第三部：下载_service文件到本地，并且修改url、revison。url：点击克隆下载，复制里面的地址。revison：用包里最新的commitiD。
第四部：添加repositories，搜索openEuler:Mainline:RISC-并添加。
第五部：返回Overview界面，等待。

结果： unresolvable: 1。有一个构建错误。

**Comment by xijing21** [comment]
unresolvable  ，将鼠标移到该状态上，可以显示提示信息，查看原因和缺少的依赖包。

任务完成，关闭issue。
