### ISSUE TITLE
[excluded练习]acpid

### ISSUE THREAD

**Issue by ShiHaoGao** [plctlab/openEuler-riscv#62]
1.在gitee上查看excluded状态包，fork到自己的仓库；
2.在gitee上自己的仓库中修改spec文件，并且commit。copy commitID 和 个人gitee的仓库地址。
2.在obs上Branch package，将包拉倒自己的obs subproject下；
3.修改_service文件中url和revision。
4.添加依赖库！
结果：
![image](https://user-images.githubusercontent.com/61191871/132086610-2b4fdbb4-6a4b-4bbc-b66e-c6334b9f9ac4.png)
这里我误将错误的版本pr了，希望管理员能发现>_<

**Comment by xijing21** [comment]
pr是可以取消的，可以取消你错误的pr请求。

**Comment by ShiHaoGao** [comment]
好的我去试试
