### ISSUE TITLE
[excluded练习]arm-trusted-firmware

### ISSUE THREAD

**Issue by YuanZheng612** [plctlab/openEuler-riscv#68]
第一步，在库中寻找excluded的包并branch package，将包拉到自己的obs subproject下
第二部，在gittee源码仓中查询相应的包fork到自己的仓库，并修改spec文件，在ExclusiveArch后添加riscv64，提交
第三部，复制gittee自己仓库中已经修改过的包的地址和commitiD，修改_service文件
第四部，等待
结果：
falied
[ 1070s] oe-RISCV-worker74-home failed "build arm-trusted-firmware.spec" at Sun Sep  5 06:44:25 UTC 2021.
分析：（根据构建日志）无法识别的命令行选项-mgeneral-regs-only    错误的退出状态。
（由于构建时间较长，中间尝试了别的包，不相信在gittee上发了一个pull request）

**Comment by YuanZheng612** [comment]
收到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wei ***@***.***&gt;; 
发送时间: 2021年9月6日(星期一) 中午11:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [plctlab/openEuler-riscv] [excluded练习]arm-trusted-firmware (#68)





 
Assigned #68 to @YuanZheng612.
 
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xijing21** [comment]
操作流程正确，完成练习任务，关闭issue
