### ISSUE TITLE
20210908 外部可见交付物汇总表

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#75]
请各位项目组成员于9.8中午之前提交2021.8.26--2021.9.8时间周期内的外部可见交付。

将可见交付以回复的方式提交到本issue中。

说明：以后每次双周会的前一天，每个月的月末，都要求大家提交自己的可见交付物，方便同步项目进展。

**Comment by zxs-un** [comment]
- [BaseOS工程仓及软件包列表](https://gitee.com/zxs-un/openEuler-port2riscv64/blob/master/doc/build-obs-baseos-repo.md)
- [BaseOS Project Config & Meta](https://gitee.com/zxs-un/openEuler-port2riscv64/blob/master/doc/build-obs-baseos-LFShost.md)
- [ubuntu 上没有 root 权限的用户搭建 QEMU RISC-V 宿主机环境](https://gitee.com/zxs-un/openEuler-port2riscv64/blob/master/doc/vm-host-no-root-on-ubuntu.md)

**Comment by liujiawei929** [comment]
- [OSC本地构建](https://gitee.com/jiawei__liu/open-euler_riscv64/blob/master/doc/OSC%E6%9C%AC%E5%9C%B0%E6%9E%84%E5%BB%BA.pdf)，目前遇到一些问题还没成功，如果有成功的同学，欢迎指导。
- [openEuler包构建相关背景知识](https://gitee.com/jiawei__liu/open-euler_riscv64/blob/master/doc/openEuler%E5%8C%85%E6%9E%84%E5%BB%BA%E7%9B%B8%E5%85%B3%E8%83%8C%E6%99%AF%E7%9F%A5%E8%AF%86.md)

**Comment by mc964203886** [comment]
更新了package的[错误报告](https://gitee.com/mc964203886/OpenEuler-Mainline-RISC-V-Error-Type-August)

**Comment by LiuYang328** [comment]
[第一周小结](https://gitee.com/LiuY328/deliverable/blob/master/README.md#%E7%AC%AC%E4%B8%80%E5%91%A8%E7%9A%84%E6%88%90%E6%9E%9C)

**Comment by YuanZheng612** [comment]
**实习一周成果：**
PR（一个包）:
[rear适配riscv64](https://github.com/plctlab/openEuler-riscv/issues/28)
构建失败（两个包、未解决）：
[arm-trusted-firmware](https://github.com/plctlab/openEuler-riscv/issues/68#event-5258496859)
gsl：构建失败原因error: Bad exit status from /var/tmp/rpm-tmp.0kkOg2 (%check)，不知道这个报错怎么修改
unresolvable（三个包、未解决）：
[log4j](https://github.com/plctlab/openEuler-riscv/issues/59)
lcr：需要添加子包，具体解决办法正在学习和研究
rpm-ostree：需要添加子包，具体解决办法正在学习和研究

学会了在线构建但还不太会solve problems，正在studing，

**Comment by YuanZheng612** [comment]
**实习一周成果：**
PR（一个包）:
[rear适配riscv64](https://github.com/plctlab/openEuler-riscv/issues/28)
构建失败（两个包、未解决）：
[arm-trusted-firmware](https://github.com/plctlab/openEuler-riscv/issues/68#event-5258496859)
gsl：构建失败原因error: Bad exit status from /var/tmp/rpm-tmp.0kkOg2 (%check)，不知道这个报错怎么修改
unresolvable（三个包、未解决）：
[log4j](https://github.com/plctlab/openEuler-riscv/issues/59)
lcr：需要添加子包，具体解决办法正在学习和研究
rpm-ostree：需要添加子包，具体解决办法正在学习和研究

学会了在线构建但还不太会solve problems，正在studing，

**Comment by ShiHaoGao** [comment]
[第一周小结](https://github.com/ShiHaoGao/workRecord/blob/main/1stWeek)
[[excluded练习]acpid](https://github.com/plctlab/openEuler-riscv/issues/62)

**Comment by asdf1113** [comment]
[尝试解决i40e包记录](https://gitee.com/lishiyangasdf/open-euler-r-v-learning-notes/blob/master/%E5%B0%9D%E8%AF%95%E8%A7%A3%E5%86%B3i40e%E5%8C%85%E8%AE%B0%E5%BD%95.md)
[本地构建abrt包和valgrind记录](https://github.com/plctlab/openEuler-riscv/issues/19)

**Comment by glutinous-rice-wine** [comment]
[本地构建libX11包成功](https://github.com/plctlab/openEuler-riscv/issues/20)
[下载osc环境，尝试修改](https://gitee.com/sticky-rice-wine/note/blob/master/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0.docx)

**Comment by Wenxiang233** [comment]
[构建情况汇总](https://github.com/Wenxiang233/PLCT_Documents/blob/main/Obs%E6%9E%84%E5%BB%BA%E6%B1%87%E6%80%BB.md)
[构建方法总结](https://github.com/Wenxiang233/PLCT_Documents/blob/main/%E6%9E%84%E5%BB%BA%E6%96%B9%E6%B3%95%E6%80%BB%E7%BB%93.md)

**Comment by xinminst** [comment]
[[构建失败] gdbus-codegen-glibmm #106](https://github.com/plctlab/openEuler-riscv/issues/106)

**Comment by MaximSuen** [comment]
- [构建失败]【已解决】 python-jaraco-collections：[链接](https://github.com/plctlab/openEuler-riscv/issues/48)

  相关PR：[链接](https://gitee.com/src-openeuler/python-jaraco-collections/pulls/2)

  OBS相关Request：[链接](https://build.openeuler.org/request/show/346)


- [构建失败]【已解决】python-mistune：[链接](https://gitee.com/openeuler/RISC-V/issues/I48GDD?from=project-issue)

  OBS相关Request：[链接](https://build.openeuler.org/request/show/345)

- 本地构建过程中遇到的问题：[链接](https://github.com/plctlab/openEuler-riscv/issues/107)

#### 笔记：

- [OBS中包的本地构建记录](https://gitee.com/maximsuen/plct-internship-notes/blob/master/6.OBS%E4%B8%AD%E5%8C%85%E7%9A%84%E6%9C%AC%E5%9C%B0%E6%9E%84%E5%BB%BA%E8%AE%B0%E5%BD%95.md)

**Comment by YuXiang-ZhuanSun** [comment]
修复openeuler中报错excluded包，添加riscv构建，但这些包仍有新的错误，进行了错误汇总上报。
| [prefetch_tuning](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/prefetch_tuning) |
| [psm](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/psm) |
| [rear](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/rear) |
| [rpm-ostree](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/rpm-ostree) |
| [rust](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/rust) |
| [sgabios](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/sgabios) |
| [shim](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/shim) |
| [spark](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/spark) |
| [spdk](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/spdk) |
| [spice](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/spice) |
| [stratovirt](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/stratovirt) |
| [syslinux](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/syslinux) |
修复openeuler中broken包，添加_serverce文件，进行构建尝试，但这些包有新的错误，进行了错误汇总上报。
| [nodejs-clone](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/nodejs-clone) |
| [openEuler-indexhtml](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/openEuler-indexhtml) |
|[glassfish-hk2](https://build.openeuler.org/package/show/openEuler:Mainline:RISC-V/glassfish-hk2)|

**Comment by YuXiang-ZhuanSun** [comment]
最近稍微有些事，稍后事情完成后，会提供更多的可见交付物。
