### ISSUE TITLE
请让实习生github出现在Assignees列表中

### ISSUE THREAD

**Issue by xijing21** [plctlab/openEuler-riscv#77]
目前新增员工和实习生无法在Assignees 中找到githubID，是否是需要将他们添加为plct成员才可行？请 @lazyparser 协助。

<html>
<body>
<!DOCTYPE html>

吕晓倩 | 测试开发 |   | lvxiaoqian | lvxiaoqian555 |  
-- | -- | -- | -- | -- | --
高世豪 | 在职实习生 | LV1 | ShihaoGao | ShiHaoGao |  
袁政 | 在职实习生 | LV1 | YuanZheng612 | YuanZheng612 |  
刘洋 | 在职实习生 | LV1 | LiuY328 | LiuYang328

</body>
</html>

**Comment by lazyparser** [comment]
都已经邀请。请查看邮件。
