### ISSUE TITLE
[xfce]桌面右上方状态栏图标无法显示

### ISSUE THREAD

**Issue by jiewu-plct** [plctlab/openEuler-riscv#80]
![Debian desktop](https://user-images.githubusercontent.com/89007492/132167864-d91f2965-ce0e-4d75-99f0-226397ed4c30.jpg)

**Comment by GeassCore** [comment]
这个是workspace，支持切换就ok，桌面打开有简单窗口显示

**Comment by jiewu-plct** [comment]
是的，对比了正常的debian, This issue is not a bug.
