### ISSUE TITLE
[xfce]浏览器界面无法正常显示中文字符

### ISSUE THREAD

**Issue by jiewu-plct** [plctlab/openEuler-riscv#81]
如网页标题，网页界面
![Uploading browser.jpg…]()

**Comment by GeassCore** [comment]
缺少中文字库，暂未找到中文包，可以使用以下命令快速修复
wget https://files.cnblogs.com/files/xiaochina/simsun.zip
unzip simsun.zip
cp simsun.ttc  /usr/share/fonts/
mkfontscale
mkfontdir
fc-cache -fv

**Comment by xijing21** [comment]
按次方法执行后，解决了中文问题：

![f8c1353c7e1bfbcd01cc70b55400eb2](https://user-images.githubusercontent.com/84754181/132339856-f73842e0-f1b4-4819-9867-5a635c54da1b.jpg)


但是执行过程中发现wget不可用，详见issue #105

**Comment by xijing21** [comment]
> 缺少中文字库，暂未找到中文包，可以使用以下命令快速修复 wget https://files.cnblogs.com/files/xiaochina/simsun.zip unzip simsun.zip cp simsun.ttc /usr/share/fonts/ mkfontscale mkfontdir fc-cache -fv

curl -o simsun.zip -L https://files.cnblogs.com/files/xiaochina/simsun.zip
