### ISSUE TITLE
[xfce]桌面右上方日历界面存在黑块问题

### ISSUE THREAD

**Issue by jiewu-plct** [plctlab/openEuler-riscv#85]
![calendar](https://user-images.githubusercontent.com/89007492/132175308-c587f216-9faf-4611-a718-62dee6dd8c30.jpg)

**Comment by xijing21** [comment]
不仅是日历，还有类似windows下的[资源管理器]中也存在此问题：

![image](https://user-images.githubusercontent.com/84754181/132207344-37a71a0b-f259-41b6-97ad-36b1ee5b7521.png)

**Comment by xijing21** [comment]
重复的issue，关闭。

详见 #63
