### ISSUE TITLE
[xfce]java小程序LuckyLudii3.3.jar在D1上无法成功运行

### ISSUE THREAD

**Issue by jiewu-plct** [plctlab/openEuler-riscv#96]
D1烧入openEuler-D1-xfce.img.bz2镜像, 在D1上执行java -jar LuckyLudii3.3.jar， java小程序LuckyLudii3.3.jar无法成功运行，该该程序在x86上可正常运行
![image](https://user-images.githubusercontent.com/89007492/132298442-fd235e7c-e48d-40f2-86e3-b4f1f5ebc5bd.png)

**Comment by jiewu-plct** [comment]
在D1上安装libX11.riscv64  xorg-x11-xauth.riscv64这2个包，然后用MobaXterm进行ssh 11X Forwarding，就可以正常运行了

**Comment by GeassCore** [comment]
> 在D1上安装libX11.riscv64和xorg-x11-xauth.riscv64这2个包，然后用MobaXterm进行ssh 11X Forwarding，就可以正常运行了

可以正常运行jar包嘛

**Comment by xijing21** [comment]
我这边运行是这样的：https://github.com/plctlab/openEuler-riscv/issues/90#issuecomment-914220786
